# Generated by Django 5.1.6 on 2025-03-01 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_generator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='yotube_link',
            new_name='youtube_link',
        ),
    ]
